name: RaceDay Simple Check

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4

name: Check files exist <- 6 spaces from left
run: | <- 8 spaces
echo "Checking..." <- 10 spaces <-- THIS ONE
ls -R <- 10 spaces <-- AND THIS ONE
echo "Workflow works!" <- 10 spaces <-- AND THIS ONE
